export const routeNames: Record<string, string> = {
  '': 'Dashboard',
  'registrations': 'Cadastros',
  'harvest': 'Safras',
  'agricultural-years': 'Ano Agrícola',
  'cultures': 'Culturas',
  'crops': 'Safras',
  'varieties': 'Variedades',
  'properties': 'Propriedades',
  'owners': 'Proprietários',
  'producers': 'Produtores',
  'areas': 'Áreas',
  'farms': 'Fazendas',
  'fields': 'Talhões',
  'plot-fields': 'Locação de Talhões',
  'matrix-freights': 'Matriz de Frete',
  'suppliers': 'Fornecedores',
  'type-suppliers': 'Tipos de Fornecedores',
  'warehouses': 'Armazéns',
  'lanyards': 'Colhedores',
  'drivers': 'Motoristas',
  'contracts': 'Contratos',
  'service-contracts': 'Contratos de Serviço',
  'generated': 'Contratos Gerados',
  'driver-contracts': 'Motorista Contrato',
  'lanyard-contracts': 'Colhedor Contrato',
  'users': 'Usuários',
  'new': 'Novo',
  'edit': 'Editar',
  'vehicles': 'Veículos',
  'fleet-groups': 'Grupos de Frotas',
  'fleet-brands': 'Marcas de Frotas',
  'fleet-models': 'Modelos de Frotas',
  'fleets': 'Frotas',
  'agricultural': 'Agrícolas',
  'operation-defensives': 'Operações de Defensivos',
  'type-operations': 'Tipos de Operações',
  'agricultural-operators': 'Operadores Agrícolas',
  'type-formulations': 'Tipo Formulação',
  'agricultural-products': 'Produto Agrícola',
  'products': 'Produtos',
  'product-groups': 'Grupos de Produtos',
  'sub-group-products': 'Sub Grupos de Produtos',
  'inventory': 'Estoque',
  'stock-locations': 'Locais de Estoque',
  'agricultural-service-types': 'Tipos de Serviço Agrícola',
  'freight-rates': 'Tarifas de Frete',
  'purpose-products': 'Finalidade de Produtos',
  'supplier-products': 'Produtos Fornecedores',
  'fuels': 'Combustíveis',
  'type-posts': 'Tipos de Postos',
  'posts': 'Postos',
  'product-posts': 'Produtos por Posto',
  'entries': 'Lançamentos',
  'entry-invoice-products': 'Nota Fiscal de Entrada',
  'closing-releases': 'Encerrantes Diários',
  'daily-releases': 'Diário de Combustível',
  'harvests': 'Colheitas',
  'harvest-releases': 'Colheitas',
  'advances': 'Adiantamentos',
  'harvesters': 'Adiantamento de Colhedor',
  'transporters': 'Adiantamento de Transportador',

  'defensives': 'Ordens de Serviços Defensivos',
  'closings': 'Fechamentos',
  'consolidation': 'Consolidação',
  'tanks': 'Tanque do Operador',
  'financial': 'Financeiro',
  'administrative-centers': 'Centros Administrativos',
  'cost-centers': 'Centro de Custo',
  'type-pay-accounts': 'Tipo Contas',
  'pay-accounts': 'Contas Pagas',
  'payroll': 'Folha de Pagamento',
  'admin': 'Administração',
  'roles': 'Perfis',
  'configs': 'Configurações',
  'fuel': 'Combustíveis e Lubrificantes',
  'stations': 'Postos',
  'station-tanks': 'Tanques',
  'station-products': 'Produtos por Posto',
  'registers': 'Registradoras',
  'register-readings': 'Leituras da Registradora',
  'gauge': 'Régua dos Tanques',
  'gauge-readings': 'Leituras da Régua',
  'fuel-entries': 'Entradas',
  'transfers': 'Transferências',
  'refuelings': 'Abastecimentos',
  'stock': 'Estoque',
  'stock-movements': 'Movimentações de Estoque',
  'stock-adjustments': 'Ajustes de Estoque',
  'reconciliation': 'Conferência de Estoque',
  'consumption': 'Consumo',
  'fleet': 'Frota',
  'meter-readings': 'Leituras de Frota',
  'oil-changes': 'Troca de Óleo',
  'maintenance-plans': 'Planos de Manutenção',
  'maintenance-records': 'Manutenções',
  'imports': 'Importação de Dados',
  'grain': 'Balança e Armazém',
  'scales': 'Balanças',
  'scale-channels': 'Canais da Balança',
  'storage-locations': 'Locais de Armazenamento',
  'transport-drivers': 'Motoristas da Balança',
  'transport-trucks': 'Caminhões da Balança',
  'farm-state-registrations': 'Inscrições Estaduais',
  'discount-types': 'Tipos de Desconto',
  'impurity-types': 'Tipos de Impureza',
  'technical-loss-configs': 'Quebra Técnica',
  'panel': 'Painel da Balança',
  'tickets': 'Portarias e Tickets',
  'receiving': 'Recebimento de Grãos',
  'shipping': 'Expedição de Grãos',
  'impurity-outputs': 'Saídas de Impurezas',
  'contract-transfers': 'Transferências de Saldo',
  'balance-assignments': 'Cessões entre Produtores',
  'balances': 'Posição de Estoque',
  'technical-losses': 'Quebras Técnicas',
  'authorizations': 'Autorizações',
  'print': 'Impressão',
  'fiscal': 'Notas Fiscais',
  'entry-invoices': 'Notas Fiscais de Entrada',
  'lubricant': 'Lubrificante',
  'defensive': 'Defensivo',
  'input': 'Insumo',
  'general': 'Geral',
  'seed': 'Semente',
  'services': 'Serviços Agrícolas',
  'workforce': 'Quadro Diário de Funcionários',
  'soil-preparation': 'Preparo do Solo',
  'input-application': 'Aplicação de Insumos',
  'firebreak-maintenance': 'Manutenção de Aceiro',
  'seed-treatments': 'Tratamento de Sementes',
  'freights': 'Fretes de Notas',
  'freight-payments': 'Pagamentos de Frete',
  'purchase-returns': 'Devoluções de Compra',
  'movements': 'Movimentações de Estoque',
  'product-outputs': 'Saídas de Produtos',
  'grain-transfers': 'Transferências de Grãos',
  'reports': 'Relatórios',
  'defensive-orders': 'Conferência de Ordens de Serviços Defensivos',
  'defensive-products': 'Conferência de Produtos por Operação',
  'defensive-products-total': 'Conferência Total de Produtos por Safra',
  'paid-accounts': 'Contas Pagas',
  'by-cost-center': 'Por Centro de Custo',
  'by-crop': 'Por Ano Agrícola/Safra',
  'consolidated': 'Consolidado de Colheita',
  'productivity': 'Produtividade',
  'plots': 'Por Talhão',
};
