import {
  Bookmark,
  Box,
  Boxes,
  Building2,
  Calendar,
  Car,
  CarFront,
  CircleDot,
  Cog,
  FileSignature,
  FileText,
  FlaskConical,
  Fuel,
  Gauge,
  Grid3X3,
  Handshake,
  Home,
  Layers,
  Layers3,
  LayoutList,
  MapPin,
  Package,
  Percent,
  Ruler,
  Scale,
  Scissors,
  Settings,
  ShoppingCart,
  Sprout,
  Tags,
  Target,
  Tractor,
  Truck,
  UserCheck,
  Warehouse,
  Wheat,
  Droplets,
} from 'lucide-react';
import type { NavigationItem } from './navigation.types';

export const registrationsMenu: NavigationItem = {
  id: 'registrations',
  title: 'Cadastros',
  icon: Settings,
  children: [
    {
      id: 'registrations.crops',
      title: 'Safras e Culturas',
      icon: Wheat,
      children: [
        { id: 'registrations.crops.years', title: 'Anos Agrícolas', path: '/registrations/harvest/agricultural-years', icon: Calendar, roles: ['SUPER', 'ADM'] },
        { id: 'registrations.crops.cultures', title: 'Culturas', path: '/registrations/harvest/cultures', icon: Sprout, roles: ['SUPER', 'ADM'] },
        { id: 'registrations.crops.varieties', title: 'Variedades', path: '/registrations/harvest/varieties', icon: Layers, roles: ['SUPER', 'ADM', 'USR'] },
        { id: 'registrations.crops.crops', title: 'Safras', path: '/registrations/harvest/crops', icon: Wheat, roles: ['SUPER', 'ADM'] },
      ],
    },
    {
      id: 'registrations.properties',
      title: 'Propriedades e Áreas',
      icon: Building2,
      children: [
        { id: 'registrations.properties.owners', title: 'Proprietários', path: '/registrations/properties/owners', icon: Building2, roles: ['SUPER', 'ADM'] },
        { id: 'registrations.properties.producers', title: 'Produtores', path: '/registrations/properties/producers', icon: UserCheck, roles: ['SUPER', 'ADM'] },
        { id: 'registrations.properties.farms', title: 'Fazendas', path: '/registrations/properties/areas/farms', icon: Home, roles: ['SUPER', 'ADM'] },
        { id: 'registrations.properties.fields', title: 'Talhões', path: '/registrations/properties/areas/fields', icon: Grid3X3, roles: ['SUPER', 'ADM'] },
        { id: 'registrations.properties.plot-fields', title: 'Locação de Talhões', path: '/registrations/properties/areas/plot-fields', icon: MapPin, roles: ['SUPER', 'ADM'] },
        { id: 'registrations.properties.state-registrations', title: 'Inscrições Estaduais', path: '/registrations/grain/farm-state-registrations', icon: FileSignature },
      ],
    },
    {
      id: 'registrations.suppliers',
      title: 'Fornecedores e Parceiros',
      icon: Package,
      children: [
        { id: 'registrations.suppliers.types', title: 'Tipos de Fornecedor', path: '/registrations/suppliers/type-suppliers', icon: Tags },
        { id: 'registrations.suppliers.suppliers', title: 'Fornecedores', path: '/registrations/suppliers/suppliers', icon: Package },
        { id: 'registrations.suppliers.drivers', title: 'Motoristas da Colheita', path: '/registrations/suppliers/drivers', icon: CarFront },
        { id: 'registrations.suppliers.lanyards', title: 'Colhedores', path: '/registrations/suppliers/lanyards', icon: Scissors },
        { id: 'registrations.suppliers.warehouses', title: 'Armazéns da Colheita', path: '/registrations/suppliers/warehouses', icon: Warehouse },
      ],
    },
    {
      id: 'registrations.contracts',
      title: 'Contratos de Prestadores',
      icon: FileText,
      children: [
        { id: 'registrations.contracts.transport', title: 'Contratos de Transportadores', path: '/registrations/suppliers/contracts/service-contracts/transport', icon: Truck },
        { id: 'registrations.contracts.harvest', title: 'Contratos de Colhedores', path: '/registrations/suppliers/contracts/service-contracts/harvest', icon: Scissors },
        { id: 'registrations.contracts.generated', title: 'Contratos Gerados', path: '/registrations/suppliers/contracts/service-contracts/generated', icon: FileText },
        { id: 'registrations.contracts.drivers', title: 'Motoristas', path: '/registrations/suppliers/contracts/drivers', icon: CarFront, hidden: true },
        { id: 'registrations.contracts.lanyards', title: 'Colhedores', path: '/registrations/suppliers/contracts/lanyards', icon: Scissors, hidden: true },
        { id: 'registrations.contracts.driver-contracts', title: 'Motorista Contrato', path: '/registrations/suppliers/contracts/driver-contracts', icon: FileText, hidden: true },
        { id: 'registrations.contracts.lanyard-contracts', title: 'Colhedor Contrato', path: '/registrations/suppliers/contracts/lanyard-contracts', icon: FileText, hidden: true },
      ],
    },
    {
      id: 'registrations.products',
      title: 'Produtos e Estoque',
      icon: Box,
      children: [
        { id: 'registrations.products.groups', title: 'Grupos de Produtos', path: '/registrations/products/product-groups', icon: Boxes },
        { id: 'registrations.products.subgroups', title: 'Subgrupos de Produtos', path: '/registrations/products/sub-group-products', icon: Layers3 },
        { id: 'registrations.products.products', title: 'Produtos', path: '/registrations/products/products', icon: Box },
        { id: 'registrations.products.supplier-products', title: 'Produtos por Fornecedor', path: '/registrations/products/supplier-products', icon: ShoppingCart },
        { id: 'registrations.products.purpose', title: 'Finalidade de Produtos', path: '/registrations/products/purpose-products', icon: Target, hidden: true },
        { id: 'registrations.products.stock-locations', title: 'Locais de Estoque', path: '/registrations/inventory/stock-locations', icon: Boxes },
      ],
    },
    {
      id: 'registrations.agricultural',
      title: 'Operações Agrícolas',
      icon: Tractor,
      children: [
        { id: 'registrations.agricultural.operation-defensives', title: 'Operações de Defensivos', path: '/registrations/agricultural/operation-defensives', icon: CircleDot },
        { id: 'registrations.agricultural.type-operations', title: 'Tipos de Operação', path: '/registrations/agricultural/type-operations', icon: CircleDot },
        { id: 'registrations.agricultural.service-types', title: 'Tipos de Serviço Agrícola', path: '/registrations/inventory/agricultural-service-types', icon: Tractor },
        { id: 'registrations.agricultural.operators', title: 'Operadores Agrícolas', path: '/registrations/agricultural/agricultural-operators', icon: Tractor },
        { id: 'registrations.agricultural.type-formulations', title: 'Tipos de Formulação', path: '/registrations/agricultural/type-formulations', icon: FlaskConical },
        { id: 'registrations.agricultural.products', title: 'Produtos Agrícolas', path: '/registrations/agricultural/agricultural-products', icon: Target },
      ],
    },
    {
      id: 'registrations.fleets',
      title: 'Frotas',
      icon: Car,
      children: [
        { id: 'registrations.fleets.groups', title: 'Grupos de Frotas', path: '/registrations/vehicles/fleet-groups', icon: LayoutList },
        { id: 'registrations.fleets.brands', title: 'Marcas', path: '/registrations/vehicles/fleet-brands', icon: Bookmark },
        { id: 'registrations.fleets.models', title: 'Modelos', path: '/registrations/vehicles/fleet-models', icon: Cog },
        { id: 'registrations.fleets.fleets', title: 'Frotas', path: '/registrations/vehicles/fleets', icon: Car },
      ],
    },
    {
      id: 'registrations.fuel',
      title: 'Combustíveis',
      icon: Fuel,
      children: [
        { id: 'registrations.fuel.stations', title: 'Postos', path: '/entries/fuel/stations', icon: Fuel },
        { id: 'registrations.fuel.tanks', title: 'Tanques', path: '/entries/fuel/station-tanks', icon: Box },
        { id: 'registrations.fuel.station-products', title: 'Produtos por Posto', path: '/entries/fuel/station-products', icon: Package },
        { id: 'registrations.fuel.registers', title: 'Registradoras', path: '/entries/fuel/registers', icon: Gauge },
        { id: 'registrations.fuel.gauge', title: 'Tabelas de Régua', path: '/entries/fuel/gauge', icon: Ruler },
      ],
    },
    {
      id: 'registrations.grain',
      title: 'Balança e Armazém',
      icon: Scale,
      children: [
        { id: 'registrations.grain.scales', title: 'Balanças', path: '/registrations/grain/scales', icon: Scale },
        { id: 'registrations.grain.channels', title: 'Canais da Balança', path: '/registrations/grain/scale-channels', icon: Gauge },
        { id: 'registrations.grain.warehouses', title: 'Armazéns de Grãos', path: '/registrations/grain/warehouses', icon: Warehouse },
        { id: 'registrations.grain.storage-locations', title: 'Locais de Armazenamento', path: '/registrations/grain/storage-locations', icon: Boxes },
        { id: 'registrations.grain.drivers', title: 'Motoristas da Balança', path: '/registrations/grain/transport-drivers', icon: CarFront },
        { id: 'registrations.grain.trucks', title: 'Caminhões da Balança', path: '/registrations/grain/transport-trucks', icon: Truck },
        { id: 'registrations.grain.discount-types', title: 'Tipos de Desconto', path: '/registrations/grain/discount-types', icon: Percent },
        { id: 'registrations.grain.impurity-types', title: 'Tipos de Impureza', path: '/registrations/grain/impurity-types', icon: Droplets },
        { id: 'registrations.grain.technical-loss', title: 'Configuração de Quebra Técnica', path: '/registrations/grain/technical-loss-configs', icon: Ruler },
      ],
    },
    {
      id: 'registrations.financial',
      title: 'Financeiro',
      icon: Building2,
      children: [
        { id: 'registrations.financial.administrative-centers', title: 'Centros Administrativos', path: '/registrations/financial/administrative-centers', icon: Building2 },
        { id: 'registrations.financial.cost-centers', title: 'Centros de Custo', path: '/registrations/financial/cost-centers', icon: Target },
        { id: 'registrations.financial.type-pay-accounts', title: 'Tipos de Pagamento', path: '/registrations/financial/type-pay-accounts', icon: Tags },
      ],
    },
    {
      id: 'registrations.logistics',
      title: 'Logística e Fretes',
      icon: Handshake,
      children: [
        { id: 'registrations.logistics.matrix-freights', title: 'Matriz de Frete', path: '/registrations/properties/areas/matrix-freights', icon: Truck, roles: ['SUPER', 'ADM'] },
        { id: 'registrations.logistics.freight-rates', title: 'Tarifas de Frete', path: '/registrations/inventory/freight-rates', icon: Truck },
      ],
    },
  ],
};
